#!/bin/sh
#
# Start volta
#

case "$1" in
  start)
 	echo "Starting @template@"
#	modprobe i2c_dev
	/root/launch_@template@.sh &>/dev/null &
#	/bin/volta &
	;;
  stop)
	echo -n "Stopping @template@"
	killall @template@
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

