ERR(2, 27, "'_define_' should not be followed by 'Component'")
ERR(2, 125, "missing parenthesis in component definition")
ERR(0, 125, "missing identifier")
ERR(0, 125, "unknown loadXML, did you mean loadFromXML?")
ERR(1, 1, "component definition outside of _main_ or _define_")
